-----------------------------------------------------
-- Script to insert into State Info Table
-----------------------------------------------------

-- Insert Data
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Alabama', 'AL', 'Montgomery', '1846','198218','George Washington Carver, who discovered more than 300 uses for peanuts');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Alaska', 'AK', 'Juneau', '1906','31275','The longest coastline in the U.S., 6,640 miles, greater than that of all other states combined');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Arizona', 'AZ', 'Phoenix', '1889','1660272','The most telescopes in the world, in Tucson');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Arkansas', 'AR', 'Little Rock', '1821','193524','The only active diamond mine in the U.S.');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('California', 'CA', 'Sacramento', '1854','508529','“General Sherman,” a 3,500-year-old tree, and a stand of bristlecone pines 4,000 years old are the worlds oldest living things');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Colorado', 'CO', 'Denver', '1867','716492','The worlds largest silver nugget (1,840 pounds) found in 1894 near Aspen');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Connecticut', 'CT', 'Hartford', '1875','124775','The first American cookbook, published in Hartford in 1796: American Cookery by Amelia Simmons');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Delaware', 'DE', 'Dover', '1777','36047','The first log cabins in North America, built in 1683 by Swedish immigrants');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Florida', 'FL', 'Tallahassee', '1824','181376','U.S. spacecraft launchings from Cape Canaveral, formerly Cape Kennedy');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Georgia', 'GA', 'Atlanta', '1868','498044','The Girl Scouts, founded in Savannah by Juliette Gordon Low in 1912');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Hawaii', 'HI', 'Honolulu', '1845','359870','The only royal palace in the U.S. (Iolani)');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Idaho', 'ID', 'Boise', '1865','205671','The longest main street in America, 33 miles, in Island Park');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Illinois', 'IL', 'Springfield', '1837','116250','The tallest building in the U.S., Sears Tower, in Chicago');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Indiana', 'IN', 'Indianapolis', '1825','867125','The famous car race: the Indy 500');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Iowa', 'IA', 'Des Moines', '1857','203433','The shortest and steepest railroad in the U.S., Dubuque: 60° incline, 296 feet');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Kansas', 'KS', 'Topeka', '1856','127473','Helium discovered in 1905 at the University of Kansas');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Kentucky', 'KY', 'Frankfort', '1792','25527','The largest underground cave in the world: 300 miles long, the Mammoth-Flint Cave system');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Louisiana', 'LA', 'Baton Rouge', '1880','225374','The most crayfish: 98% of the worlds crayfish');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Maine', 'ME', 'Augusta', '1832','19136','The most easterly point in the U.S., West Quoddy Head1');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Maryland', 'MD', 'Annapolis', '1694','38394','The first umbrella factory in the U.S., 1928, Baltimore');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Massachusetts', 'MA', 'Boston', '1630','694583','The first World Series, 1903: the Boston “Americans” (became the Red Sox in 1908) vs. the Pittsburg Pirates (Pittsburgh had no “h” between 1890–1911)');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Michigan', 'MI', 'Lansing', '1847','114297','The Cereal Bowl of America, Battle Creek, produces most cereal in the U.S.');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Minnesota', 'MN', 'Saint Paul', '1849','285068','The oldest rock in the world, 3.8 billion years old, found in Minnesota River valley');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Mississippi', 'MS', 'Jackson', '1821','173514','Coca-Cola, first bottled in 1894 in Vicksburg');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Missouri', 'MO', 'Jefferson City', '1826','43079','Mark Twain and some of his characters, such as Tom Sawyer and Huckleberry Finn');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Montana', 'MT', 'Helena', '1875','28190','Grasshopper Glacier, named for the grasshoppers that can still be seen frozen in ice');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Nebraska', 'NE', 'Lincoln', '1867','258379','The only roller skating museum in the world, in Lincoln');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Nevada', 'NV', 'Carson City', '1861','55274','Rare fish such as the Devils Hole pup, found only in Devils Hole, and other rare fish from prehistoric lakes; also the driest state');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('New Hampshire', 'NH', 'Concord', '1808','42695','Artificial rain, first used near Concord in 1947 to fight a forest fire');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('New Jersey', 'NJ', 'Trenton', '1784','84913','The worlds first drive-in movie theater, built in 1933 near Camden');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('New Mexico', 'NM', 'Santa Fe', '1610','75764','“Smokey Bear,” a cub orphaned by fire in 1950, buried in Smokey Bear Historical State Park in 1976');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('New York', 'NY', 'Albany', '1797','97856','The first presidential inauguration: George Washington took the oath of office in New York City on April 30, 1789.');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('North Carolina', 'NC', 'Raleigh', '1792','403892','Virginia Dare, the first English child born in America, on Roanoake Island in 1587');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('North Dakota', 'ND', 'Bismarck', '1883','61272','The geographic center of North America, in Pierce County, near Balta');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Ohio', 'OH', 'Columbus', '1816','892553','The first electric traffic lights, invented and installed in Cleveland in 1914');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Oklahoma', 'OK', 'Oklahoma City', '1910','649021','The first parking meter, installed in Oklahoma City in 1935');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Oregon', 'OR', 'Salem', '1855','154637','The worlds smallest park, totaling 452 inches, created in Portland on St. Patricks Day for leprechauns and snail races');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Pennsylvania', 'PA', 'Harrisburg', '1812','49528','The first magazine in America: the American Magazine, published in Philadelphia for 3 months in 1741');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Rhode Island', 'RI', 'Providence', '1900','178042','Rhode Island Red chickens, first bred in 1854; the start of poultry as a major American industry');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('South Carolina', 'SC', 'Columbia', '1786','129272','The first tea farm in the U.S., created in 1890 near Summerville');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('South Dakota', 'SD', 'Pierre', '1889','13646','The worlds largest natural, indoor warmwater pool, Evans Plunge in Hot Springs');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Tennessee', 'TN', 'Nashville', '1826','691243','Graceland, the estate and gravesite of Elvis Presley');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Texas', 'TX', 'Austin', '1839','964254','NASA, in Houston, headquarters for all piloted U.S. space projects');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Utah', 'UT', 'Salt Lake City', '1858','186440','Rainbow Bridge, the largest natural stone bridge in the world, 290 feet high, 275 feet across');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Vermont', 'VT', 'Montpelier', '1805','7855','The largest production of maple syrup in the U.S.');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Virginia', 'VA', 'Richmond', '1780','204214','The only full-length statue of George Washington, placed in capitol in 1796');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Washington', 'WA', 'Olympia', '1853','46478','Lunar Rover, the vehicle used by astronauts on the moon; Boeing, in Seattle, makes aircraft and spacecraft');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('West Virginia', 'WV', 'Charleston', '1885','51400','Marbles; most of the countrys glass marbles made around Parkersburg');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Wisconsin', 'WI', 'Madison', '1838','233209','The typewriter, invented in Milwaukee in 1867');
INSERT INTO STATE_INFO (State_Name, State_Abrv, State_Capital, Capital_Since, Capital_Population, Fun_Fact) VALUES ('Wyoming', 'WY', 'Cheyenne', '1869','59466','The “Register of the Desert,” a huge granite boulder covering 27 acres with 5,000 early pioneer names carved on it');
